mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090

proxies:
  - name: "masque"
    type: masque
    server: "162.159.199.2"
    port: 500
    private-key: "MHcCAQEEILI1eOtnbEIh89Fj4yNDuFR6UjayCKI3NdLl3DhetimWoAoGCCqGSM49AwEHoUQDQgAEgyXrE8v+hHsHy3ewSb3WcRjYgCrM9T9hiE0Uv6k2DZ1+4kefrDT9v1Q/8wdRigTf6t6gGNUV8W+IUMdrfUt+9g=="
    public-key: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIaU7MToJm9NKp8YfGxR6r+/h4mcG7SxI8tsW8OR1A5tv/zCzVbCRRh2t87/kxnP6lAy0lkr7qYwu+ox+k3dr6w=="
    ip: "172.16.0.2"
    ipv6: "2606:4700:110:84c0:163a:4914:a0ad:3342"
    mtu: 1280
    udp: true
    remote-dns-resolve: true
    dns: [1.1.1.1, 8.8.8.8]
    congestion-controller: bbr

proxy-groups:
  - name: "SELECT"
    type: select
    proxies:
      - masque

rules:
  - GEOIP,CN,DIRECT
  - MATCH,SELECT
